// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <ostream>
#include <string_view>

#include "evo/cli.hpp"
#include "evo/status.hpp"

namespace evo {

// Raw output is byte exact. FASTA output is strict and round-trippable through
// stream_sequence_file, so non-IUPAC generated bytes fail explicitly.
[[nodiscard]] Status write_generated_sequence(
    std::ostream &output, std::string_view sequence,
    GenerationOutputFormat format, std::string_view name);

} // namespace evo
