model_id: evo2_20b
model_name: shc-evo2-20b
vocab_size: 512
hidden_size: 8192
num_filters: 8192
hcl_layer_idxs: [2,6,9,13,16,20,23]
hcm_layer_idxs: [1,5,8,12,15,19,22]
hcs_layer_idxs: [0,4,7,11,14,18,21]
attn_layer_idxs: [3,10,17]
hcm_filter_length: 128
hcl_filter_groups: 8192
hcm_filter_groups: 512
hcs_filter_groups: 512
hcs_filter_length: 7
num_layers: 24
short_filter_length: 3
num_attention_heads: 64
short_filter_bias: false
eps: 0.000001
state_size: 16
rotary_emb_base: 1000000
rotary_emb_scaling_factor: 128
use_interpolated_rotary_pos_emb: true
inner_size_multiple_of: 128
inner_mlp_size: 22528
proj_groups: 1
column_split_hyena: false
column_split: true
interleave: true
evo2_style_activations: true
use_fp8_input_projections: true
model_parallel_size: 1
pipe_parallel_size: 1
tie_embeddings: true
mha_out_proj_bias: true
hyena_out_proj_bias: true
hyena_flip_x1x2: false
qkv_proj_bias: false
max_seqlen: 1048576
max_batch_size: 1
final_norm: true
tokenizer_type: CharLevelTokenizer
prefill_style: fft
mlp_activation: gelu
