#!/usr/bin/env python3
"""Run the official Evo 2 greedy continuation identity gate."""

import argparse
import csv
import hashlib
import json
import subprocess
import time
from pathlib import Path


def read_sequences(path: Path) -> list[str]:
    with path.open(encoding="utf-8-sig", newline="") as input_file:
        reader = csv.reader(input_file)
        next(reader)
        sequences = [row[0] for row in reader if row]
    if not sequences:
        raise ValueError(f"no prompt sequences found in {path}")
    return sequences


def split_prompt_target(sequence: str, token_count: int) -> tuple[str, str]:
    midpoint = 2 * (len(sequence) // 4)
    return sequence[:midpoint], sequence[midpoint : midpoint + token_count]


def identity(generated: bytes, target: str) -> float:
    target_bytes = target.encode()
    compared = min(len(generated), len(target_bytes))
    if compared == 0:
        raise ValueError("cannot calculate identity for an empty continuation")
    matches = sum(
        left == right
        for left, right in zip(
            generated[:compared], target_bytes[:compared], strict=True
        )
    )
    return 100.0 * matches / compared


def parse_metrics(stderr: bytes) -> dict[str, object]:
    prefix = b"evo2c_metrics "
    for line in reversed(stderr.splitlines()):
        if line.startswith(prefix):
            return json.loads(line[len(prefix) :])
    raise RuntimeError("evo2c did not emit its metrics record")


def write_json_atomic(path: Path, payload: dict[str, object]) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as input_file:
        while chunk := input_file.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def generate(
    binary: Path,
    model: Path,
    prompt: str,
    token_count: int,
    context: int,
    gpus: str,
    logits_path: Path,
    force_prompt_threshold: int,
) -> tuple[bytes, dict[str, object]]:
    result = subprocess.run(
        [
            str(binary),
            "-m",
            str(model),
            "-p",
            prompt,
            "-n",
            str(token_count),
            "--ctx",
            str(context),
            "--gpu",
            gpus,
            "--top-k",
            "1",
            "--top-p",
            "1",
            "--temp",
            "1",
            "--seed",
            "1",
            "--force-prompt-threshold",
            str(force_prompt_threshold),
            "--dump-logits",
            str(logits_path),
        ],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"evo2c generation failed ({result.returncode}):\n"
            f"{result.stderr.decode(errors='replace')}"
        )
    if len(result.stdout) != token_count:
        raise RuntimeError(
            f"expected {token_count} generated bytes, got {len(result.stdout)}"
        )
    return result.stdout, parse_metrics(result.stderr)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--binary", required=True, type=Path)
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--model-sha256")
    parser.add_argument("--prompts", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--num-tokens", type=int, default=500)
    parser.add_argument("--ctx", type=int, default=8192)
    parser.add_argument("--gpu", default="0,1,2,3")
    parser.add_argument("--force-prompt-threshold", type=int, default=3000)
    parser.add_argument("--expected-identity", type=float, default=91.15)
    parser.add_argument("--tolerance", type=float, default=3.0)
    parser.add_argument("--skip-mean-gate", action="store_true")
    parser.add_argument("--summarize-existing", action="store_true")
    parser.add_argument("--repeat-first", action="store_true")
    parser.add_argument("--start-index", type=int, default=0)
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()
    if args.num_tokens <= 0:
        parser.error("--num-tokens must be positive")
    if args.limit is not None and args.limit <= 0:
        parser.error("--limit must be positive")
    if args.start_index < 0:
        parser.error("--start-index must be nonnegative")
    if args.force_prompt_threshold <= 0:
        parser.error("--force-prompt-threshold must be positive")
    if args.summarize_existing and args.repeat_first:
        parser.error("--summarize-existing cannot repeat generation")
    if args.model_sha256 is not None:
        args.model_sha256 = args.model_sha256.lower()
        if len(args.model_sha256) != 64 or any(
            digit not in "0123456789abcdef" for digit in args.model_sha256
        ):
            parser.error("--model-sha256 must contain 64 hexadecimal characters")

    sequences = list(enumerate(read_sequences(args.prompts)))
    sequences = sequences[args.start_index :]
    if args.limit is not None:
        sequences = sequences[: args.limit]
    if not sequences:
        parser.error("--start-index selects no prompt sequences")
    artifact_dir = args.output.parent / f"{args.output.stem}-artifacts"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, object]] = []
    started = time.monotonic()
    first_generated: bytes | None = None
    first_prompt = ""
    for index, sequence in sequences:
        prompt, target = split_prompt_target(sequence, args.num_tokens)
        prompt_path = artifact_dir / f"prompt-{index}.bin"
        target_path = artifact_dir / f"target-{index}.bin"
        generated_path = artifact_dir / f"generated-{index}.bin"
        logits_path = artifact_dir / f"logits-{index}.npy"
        prompt_path.write_bytes(prompt.encode())
        target_path.write_bytes(target.encode())
        record_path = artifact_dir / f"record-{index}.json"
        if args.summarize_existing:
            if (
                not generated_path.is_file()
                or not logits_path.is_file()
                or generated_path.stat().st_size != args.num_tokens
            ):
                raise RuntimeError(
                    f"prompt {index} does not have complete existing artifacts"
                )
            generated = generated_path.read_bytes()
            metrics = None
            if record_path.is_file():
                existing_record = json.loads(
                    record_path.read_text(encoding="utf-8")
                )
                metrics = existing_record.get("metrics")
        else:
            generated, metrics = generate(
                args.binary,
                args.model,
                prompt,
                args.num_tokens,
                args.ctx,
                args.gpu,
                logits_path,
                args.force_prompt_threshold,
            )
            generated_path.write_bytes(generated)
        if index == 0:
            first_generated = generated
            first_prompt = prompt
        record = {
            "index": index,
            "sequence_length": len(sequence),
            "prompt_length": len(prompt),
            "target_length": len(target),
            "generated_sha256": hashlib.sha256(generated).hexdigest(),
            "prompt_path": str(prompt_path),
            "target_path": str(target_path),
            "generated_path": str(generated_path),
            "logits_path": str(logits_path),
            "identity_percent": identity(generated, target),
            "metrics": metrics,
        }
        records.append(record)
        if not args.summarize_existing:
            write_json_atomic(record_path, record)
        print(
            f"prompt {index}: identity={record['identity_percent']:.4f}% "
            f"sha256={record['generated_sha256']}",
            flush=True,
        )

    deterministic = None
    if args.repeat_first:
        assert first_generated is not None
        repeated, repeated_metrics = generate(
            args.binary,
            args.model,
            first_prompt,
            args.num_tokens,
            args.ctx,
            args.gpu,
            artifact_dir / "repeat-first-logits.npy",
            args.force_prompt_threshold,
        )
        (artifact_dir / "repeat-first-generated.bin").write_bytes(repeated)
        deterministic = {
            "byte_exact": repeated == first_generated,
            "repeated_sha256": hashlib.sha256(repeated).hexdigest(),
            "metrics": repeated_metrics,
        }

    mean_identity = sum(
        float(record["identity_percent"]) for record in records
    ) / len(records)
    passed = (
        (
            args.skip_mean_gate
            or abs(mean_identity - args.expected_identity) <= args.tolerance
        )
        and (deterministic is None or bool(deterministic["byte_exact"]))
    )
    report = {
        "schema": "evo2c.quality_gate.v1",
        "binary": str(args.binary),
        "binary_sha256": sha256_file(args.binary),
        "model": str(args.model),
        "model_sha256": args.model_sha256,
        "prompts": str(args.prompts),
        "num_tokens": args.num_tokens,
        "context": args.ctx,
        "gpus": args.gpu,
        "start_index": args.start_index,
        "force_prompt_threshold": args.force_prompt_threshold,
        "summarized_existing": args.summarize_existing,
        "expected_identity_percent": args.expected_identity,
        "tolerance_percent": args.tolerance,
        "mean_gate_enforced": not args.skip_mean_gate,
        "mean_identity_percent": mean_identity,
        "deterministic_repeat": deterministic,
        "records": records,
        "elapsed_seconds": time.monotonic() - started,
        "passed": passed,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_json_atomic(args.output, report)
    print(
        f"mean identity={mean_identity:.4f}% "
        f"expected={args.expected_identity:.2f}±{args.tolerance:.2f}; "
        f"passed={passed}"
    )
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
